### ISSUE TITLE
db.createWriteStream is now removed.

### ISSUE THREAD

**Issue by kmod-midori** [then/then-levelup#2]
https://github.com/level/levelup#what-happened-to-dbcreatewritestream

Trying to bind to db.createWriteStream now creates an error.

**Comment by breezewish** [comment]
+1 please fix this

**Comment by edef1c** [comment]
@ForbesLindesay Can you npm publish v1.0.2?

**Comment by phaux** [comment]
**Please publish this**

**Comment by c0b41** [comment]
@ForbesLindesay new patch not published?

**Comment by stuartpb** [comment]
See #3
